/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chris' at '12/4/16 11:03 AM' with Gradle 3.1
 *
 * @author chris, @date 12/4/16 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
