import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'chris' at '12/4/16 11:03 AM' with Gradle 3.1
 *
 * @author chris, @date 12/4/16 11:03 AM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
